config/routes.rb
Rails.application.routes.draw do
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  root 'simple_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Janikapp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Raleway|Roboto+Slab|Oswald|Playfair+Display|Cinzel+Decorative" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="Janikhubka navbar-brand navbar-nav">
          <%= link_to "Bike Berlin", root_path %>
        </div> <!--end Janikhubka -->
      </div> <!-- end navbar-header-->
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", simple_pages_about_path %></li>
          <li><%= link_to "Contact", simple_pages_contact_path %></li>
        </ul>
        </div>
      </div> <!-- end container-fluid-->
    </nav> <!-- end navbar -->

  <%= yield %>
  <footer>
    &copy; 2018 Bike-Berlin
  </footer>
</body>
</html>

app/views/simple_pages/about.html.erb
<h1>Welcome to Bike Berlin</h1>
<h2>Your source for used bikes in Berlin</h2>
<p>Welcome! The date and time is <%= Time.now %></p>

app/views/simple_pages/contact.html.erb
<h1>Hello! Welcome to my App!</h1>
<p>My name is Janik Hubka and I will add my contact details soon...</p>
<p>For rental inquiries please call: 0123/4567890</p>

app/views/simple_pages/index.html.erb
<h1>Welcome to Bike Berlin</h1>
<h2>--Your source for used bikes in Berlin--</h2>
<p>This website is under maintainance... Please come back soon!</p>


<%= image_tag("racebike.jpg", class: "img-responsive my-image") %>